# -*- coding: utf-8 -*-
#
# Copyright (c) ZeroC, Inc. All rights reserved.
#
#
# Ice version 3.7.3
#
# <auto-generated>
#
# Generated from file `Printer.ice'
#
# Warning: do not edit this file.
#
# </auto-generated>
#

from sys import version_info as _version_info_
import Ice, IcePy

# Start of module Demo
_M_Demo = Ice.openModule('Demo')
__name__ = 'Demo'

_M_Demo._t_Printer = IcePy.defineValue('::Demo::Printer', Ice.Value, -1, (), False, True, None, ())

if 'PrinterPrx' not in _M_Demo.__dict__:
    _M_Demo.PrinterPrx = Ice.createTempClass()
    class PrinterPrx(Ice.ObjectPrx):

        def printString(self, texto, context=None):
            return _M_Demo.Printer._op_printString.invoke(self, ((texto, ), context))

        def printStringAsync(self, texto, context=None):
            return _M_Demo.Printer._op_printString.invokeAsync(self, ((texto, ), context))

        def begin_printString(self, texto, _response=None, _ex=None, _sent=None, context=None):
            return _M_Demo.Printer._op_printString.begin(self, ((texto, ), _response, _ex, _sent, context))

        def end_printString(self, _r):
            return _M_Demo.Printer._op_printString.end(self, _r)

        def printUpperCase(self, texto, context=None):
            return _M_Demo.Printer._op_printUpperCase.invoke(self, ((texto, ), context))

        def printUpperCaseAsync(self, texto, context=None):
            return _M_Demo.Printer._op_printUpperCase.invokeAsync(self, ((texto, ), context))

        def begin_printUpperCase(self, texto, _response=None, _ex=None, _sent=None, context=None):
            return _M_Demo.Printer._op_printUpperCase.begin(self, ((texto, ), _response, _ex, _sent, context))

        def end_printUpperCase(self, _r):
            return _M_Demo.Printer._op_printUpperCase.end(self, _r)

        def printLowerCase(self, texto, context=None):
            return _M_Demo.Printer._op_printLowerCase.invoke(self, ((texto, ), context))

        def printLowerCaseAsync(self, texto, context=None):
            return _M_Demo.Printer._op_printLowerCase.invokeAsync(self, ((texto, ), context))

        def begin_printLowerCase(self, texto, _response=None, _ex=None, _sent=None, context=None):
            return _M_Demo.Printer._op_printLowerCase.begin(self, ((texto, ), _response, _ex, _sent, context))

        def end_printLowerCase(self, _r):
            return _M_Demo.Printer._op_printLowerCase.end(self, _r)

        def countCharacters(self, texto, context=None):
            return _M_Demo.Printer._op_countCharacters.invoke(self, ((texto, ), context))

        def countCharactersAsync(self, texto, context=None):
            return _M_Demo.Printer._op_countCharacters.invokeAsync(self, ((texto, ), context))

        def begin_countCharacters(self, texto, _response=None, _ex=None, _sent=None, context=None):
            return _M_Demo.Printer._op_countCharacters.begin(self, ((texto, ), _response, _ex, _sent, context))

        def end_countCharacters(self, _r):
            return _M_Demo.Printer._op_countCharacters.end(self, _r)

        @staticmethod
        def checkedCast(proxy, facetOrContext=None, context=None):
            return _M_Demo.PrinterPrx.ice_checkedCast(proxy, '::Demo::Printer', facetOrContext, context)

        @staticmethod
        def uncheckedCast(proxy, facet=None):
            return _M_Demo.PrinterPrx.ice_uncheckedCast(proxy, facet)

        @staticmethod
        def ice_staticId():
            return '::Demo::Printer'
    _M_Demo._t_PrinterPrx = IcePy.defineProxy('::Demo::Printer', PrinterPrx)

    _M_Demo.PrinterPrx = PrinterPrx
    del PrinterPrx

    _M_Demo.Printer = Ice.createTempClass()
    class Printer(Ice.Object):

        def ice_ids(self, current=None):
            return ('::Demo::Printer', '::Ice::Object')

        def ice_id(self, current=None):
            return '::Demo::Printer'

        @staticmethod
        def ice_staticId():
            return '::Demo::Printer'

        def printString(self, texto, current=None):
            raise NotImplementedError("servant method 'printString' not implemented")

        def printUpperCase(self, texto, current=None):
            raise NotImplementedError("servant method 'printUpperCase' not implemented")

        def printLowerCase(self, texto, current=None):
            raise NotImplementedError("servant method 'printLowerCase' not implemented")

        def countCharacters(self, texto, current=None):
            raise NotImplementedError("servant method 'countCharacters' not implemented")

        def __str__(self):
            return IcePy.stringify(self, _M_Demo._t_PrinterDisp)

        __repr__ = __str__

    _M_Demo._t_PrinterDisp = IcePy.defineClass('::Demo::Printer', Printer, (), None, ())
    Printer._ice_type = _M_Demo._t_PrinterDisp

    Printer._op_printString = IcePy.Operation('printString', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0),), (), ((), IcePy._t_string, False, 0), ())
    Printer._op_printUpperCase = IcePy.Operation('printUpperCase', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0),), (), ((), IcePy._t_string, False, 0), ())
    Printer._op_printLowerCase = IcePy.Operation('printLowerCase', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0),), (), ((), IcePy._t_string, False, 0), ())
    Printer._op_countCharacters = IcePy.Operation('countCharacters', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0),), (), ((), IcePy._t_int, False, 0), ())

    _M_Demo.Printer = Printer
    del Printer

# End of module Demo
